public class CaresoftAgent {
	@AuraEnabled public Integer id;
    @AuraEnabled public string username;
    @AuraEnabled public string email;
    @AuraEnabled public string phone_no;
    @AuraEnabled public string agent_id;
    @AuraEnabled public string created_at;
    @AuraEnabled public string updated_at;
    @AuraEnabled public Integer group_id;
    @AuraEnabled public string group_name;
    @AuraEnabled public Integer role_id;
    @AuraEnabled public string login_status;
    @AuraEnabled public string call_status;
}